
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dnumgis/rasputin:latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy dependencies
      run: |
          cp -rf /root/lib/* lib/

    - name: Install
      run: |
          python3 setup.py install

    - name: Set Data Dir
      run: |
          echo "::set-env name=RASPUTIN_DATA_DIR::/__w/rasputin/rasputin/examples/example_data"

    - name: Rasputin Store
      run: |
          rasputin_store -x 24.015 24.035 24.035 24.015 -y 71.085 71.085 71.07 71.07 -ratio 1.0 -land-type-partition corine ingoya_test

    - name: Rasputin Web
      run: |
          rasputin_web -output examples/example_data/web/ingoya_test -material examples/example_data/materials/material.yaml  ingoya_test

    - name: Run tests
      run: |
          pytest tests/*
